/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-50': 'var(--primary-50)',
        'primary-100': 'var(--primary-100)',
        'primary-200': 'var(--primary-200)',
        'primary-300': 'var(--primary-300)',
        'primary-400': 'var(--primary-400)',
        'primary-500': 'var(--primary-500)',
        'primary-600': 'var(--primary-600)',
        'primary-700': 'var(--primary-700)',
        'primary-800': 'var(--primary-800)',
        'primary-900': 'var(--primary-900)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border: 'var(--border)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        success: 'var(--success)',
        'success-light': 'var(--success-light)',
        'success-text': 'var(--success-text)',
        warning: 'var(--warning)',
        'warning-light': 'var(--warning-light)',
        'warning-text': 'var(--warning-text)',
        danger: 'var(--danger)',
        'danger-light': 'var(--danger-light)',
        'danger-text': 'var(--danger-text)',
        info: 'var(--info)',
        'info-light': 'var(--info-light)',
        'info-text': 'var(--info-text)',
      },
      fontFamily: {
        display: ['Oswald', 'Helvetica Neue', 'Arial Narrow', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
