version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: ridgeway-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: StrongMongoPass@123
      MONGO_INITDB_DATABASE: ridgeway
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis:7-alpine
    container_name: ridgeway-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --requirepass StrongRedisPass@123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  mongodb_config:
  redis_data:
